# Generated by Django 5.2.6 on 2025-10-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_is_paid_appointment_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
