# Generated by Django 5.2.6 on 2025-10-23 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appointment_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'style', 'datetime'), name='uniq_user_style_datetime_when_user'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('contact_email', ''), _negated=True)), fields=('contact_email', 'style', 'datetime'), name='uniq_guest_email_style_datetime_when_email'),
        ),
    ]
