# Generated by Django 5.2.6 on 2025-10-25 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_appointment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=40)),
                ('preferred_stylist', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='uniq_user_style_datetime_when_user',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='uniq_guest_email_style_datetime_when_email',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'style', 'datetime'), name='unique_user_style_when_datetime'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('contact_email', ''), _negated=True), ('contact_email__isnull', False)), fields=('contact_email', 'style', 'datetime'), name='unique_guest_email_style_when_datetime'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
