# Generated by Django 5.2.6 on 2025-11-22 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_user_style_when_datetime',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_guest_email_style_when_datetime',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False), models.Q(('status__iexact', 'cancelled'), _negated=True)), fields=('user', 'style', 'datetime'), name='unique_user_style_when_datetime_active'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), ('contact_email__isnull', False), models.Q(('contact_email__exact', ''), _negated=True), models.Q(('status__iexact', 'cancelled'), _negated=True)), fields=('contact_email', 'style', 'datetime'), name='unique_guest_email_style_when_datetime_active'),
        ),
    ]
